### Dataset parameters
NUMBER_OF_TRAIN = 8000
NUMBER_OF_TEST = 2000
MAX_TENSOR_SIZE = 131072
DEFAULT_WIN_LENGTH = 0.04
DEFAULT_WIN_STEPS = 0.01
DEFAULT_N_MELS = 20


### Model parameters
INPUT_LENGTH = int(MAX_TENSOR_SIZE // (32000 * DEFAULT_WIN_STEPS) + 1)
INPUT_SIZE = (INPUT_LENGTH, DEFAULT_N_MELS)
D_MODEL = 128
N_HEAD = 4
NUM_ENCODER_LAYERS = 2
NUM_DECODER_LAYERS = 2
loss = "pit_mse"


### Training parameters
BATCH_SIZE = 8
NUM_EPOCHS = 10
LEARNING_RATE = 1e-3
